/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-01-20 22:49:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lesboucles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Boucles</title>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body bgcolor=white>\r\n");
      out.write("        <h1>Exercices sur les boucles</h1>\r\n");
      out.write("        <form action=\"#\" method=\"post\">\r\n");
      out.write("            <label for=\"inputValeur\">Saisir le nombre d'étoiles : </label>\r\n");
      out.write("            <input type=\"text\" id=\"inputValeur\" name=\"valeur\" required>\r\n");
      out.write("            <div>\r\n");
      out.write("                <label for=\"exercice\">Exercice</label>\r\n");
      out.write("                <select name=\"exercice\" id=\"exercice\" required>\r\n");
      out.write("                    <option value=\"\">Selectionnez l'exercice</option>\r\n");
      out.write("                    <option value=\"exo1\">Exercice 1</option>\r\n");
      out.write("                    <option value=\"exo2\">Exercice 2</option>\r\n");
      out.write("                    <option value=\"exo3\">Exercice 3</option>\r\n");
      out.write("                    <option value=\"exo4\">Exercice 4</option>\r\n");
      out.write("                    <option value=\"exo5\">Exercice 5</option>\r\n");
      out.write("                    <option value=\"exo6\">Exercice 6</option>\r\n");
      out.write("                    <option value=\"exo7\">Exercice 7</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"submit\" value=\"Afficher\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        ");
 
            String valeur = request.getParameter("valeur");
            String exercice = request.getParameter("exercice");
            if (valeur != null && !valeur.isEmpty()){
                int cpt = Integer.parseInt(valeur);
        
      out.write("\r\n");
      out.write("            ");
 switch(exercice){
                   case "exo1": 
      out.write("\r\n");
      out.write("                    ");
 for (int i = 0 ; i < cpt ; i++){ 
      out.write("\r\n");
      out.write("                        ");
 for (int j = 0 ; j < cpt ; j++){ 
      out.write('*');
 } 
      out.write("\r\n");
      out.write("                        <br>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <h2>Exercice 1 : Le carré d'étoiles</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de produire un carré d'étoile</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>*****</br>*****</br>*****</br>*****</br>*****</p>\r\n");
      out.write("                ");
 break; 
                   case "exo2": 
      out.write("\r\n");
      out.write("                   ");
 for ( int i = 0; i < cpt; i++){ 
                    for( int j = 0; j< i+1; j++){ 
      out.write('*');
 }
                    
      out.write("<br>");

                    } 
      out.write("\r\n");
      out.write("                    <h2>Exercice 2 : Triangle rectangle gauche</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de produire un triangle rectangle aligné\r\n");
      out.write("                        sur la gauche</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>*</br>**</br>***</br>****</br>*****</p>\r\n");
      out.write("                ");
 break; 
                   case "exo3": 
      out.write("\r\n");
      out.write("                ");
 for ( int i=cpt; i > 0; i--){ for( int j=i; j>0 ; j--){ 
      out.write('*');
 } 
      out.write("<br>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    <h2>Exercice 3 : Triangle rectangle inversé</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de produire un triangle rectangle aligné\r\n");
      out.write("                        sur la gauche</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>*****</br>****</br>***</br>**</br>*</p>\r\n");
      out.write("                ");
 break; 
                   case "exo4": 
      out.write("\r\n");
      out.write("                    <h2>Exercice 4 : Triangle rectangle 2</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de produire un triangle rectangle aligné\r\n");
      out.write("                        sur la droite</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**</br>&nbsp;&nbsp;&nbsp;&nbsp;***</br>&nbsp;&nbsp;****</br>*****\r\n");
      out.write("                    </p>\r\n");
      out.write("                ");
 break; 
                   case "exo5": 
      out.write("\r\n");
      out.write("                    <h2>Exercice 5 : Triangle isocele</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de produire un triangle rectangle aligné\r\n");
      out.write("                        sur la droite</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>&nbsp;&nbsp;&nbsp;&nbsp;*</br>&nbsp;&nbsp;&nbsp;**</br>&nbsp;&nbsp;***</br>&nbsp;****</br>*****\r\n");
      out.write("                    </p>\r\n");
      out.write("                ");
 break; 
                   case "exo6": 
      out.write("\r\n");
      out.write("                    <h2>Exercice 6 : Le demi losange</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de produire un losange</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**</br>&nbsp;&nbsp;&nbsp;&nbsp;***</br>&nbsp;&nbsp;****</br>*****\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>*****</br>&nbsp;&nbsp;****</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*\r\n");
      out.write("                    </p>\r\n");
      out.write("                ");
 break; 
                   case "exo7": 
      out.write("\r\n");
      out.write("                    <h2>Exercice 7 : La table de multiplication</h2>\r\n");
      out.write("                    <p>Ecrire le code afin de créser une table de multiplication</p>\r\n");
      out.write("                    <p>Exemple si l'utilisateur saisie le valeur 5</p>\r\n");
      out.write("                    <p>5 x 1 = 5</p>\r\n");
      out.write("                    <p>5 x 2 = 10</p>\r\n");
      out.write("                    <p>5 x 3 = 15</p>\r\n");
      out.write("                    <p>5 x 4 = 20</p>\r\n");
      out.write("                    <p>5 x 5 = 25</p>\r\n");
      out.write("                ");
 break; 
                   default:
                break;}
      out.write("\r\n");
      out.write("        ");
 
            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("                                                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <p><a href=\"index.html\">Retour au sommaire</a></p>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
